[platformio]
default_envs = esp32dev

[env:esp32-s2-saola-1]
platform = espressif32
board = esp32-s2-saola-1
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
lib_deps =
    https://github.com/me-no-dev/ESPAsyncWebServer.git
monitor_filters = send_on_enter
build_flags = -DI2C_SDA=10 -DI2C_SCL=11

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
lib_deps =
    https://github.com/me-no-dev/ESPAsyncWebServer.git
build_flags = -DI2C_SDA=21 -DI2C_SCL=22
